import React from 'react'
import ReactDOM from 'react-dom' /* This is the main page */
import App from './App';

const images = {
    // Unknown Card
    unknowncard: require('./resources/axiecards/unknown.png'),

    // Horns 
    anemonehead: require('./resources/axiecards/aquaponics.png'),
    antenna: require('./resources/axiecards/bug-signal.png'),
    shoalstar: require('./resources/axiecards/star-shuriken.png'),
    acrobatic: require('./resources/axiecards/acrobatic.png'),
    babylonia: require('./resources/axiecards/shell-jab.png'),
    bambooshoot: require('./resources/axiecards/bamboo-clan.png'),
    beech: require('./resources/axiecards/wooden-stab.png'),
    bumpy: require('./resources/axiecards/overgrow-keratin.png'),
    cactus: require('./resources/axiecards/prickly-trap.png'),
    candybabylonia: require('./resources/axiecards/shell-jab.png'),
    caterpillars: require('./resources/axiecards/grub-surprise.png'),
    cerastes: require('./resources/axiecards/surprise-invasion.png'),
    clamshell: require('./resources/axiecards/clam-slash.png'),
    cuckoo: require('./resources/axiecards/cockadoodledoo.png'),
    dualblade: require('./resources/axiecards/sinister-strike.png'),
    eggshell: require('./resources/axiecards/eggbomb.png'),
    featherspear: require('./resources/axiecards/feather-lunge.png'),
    goldenbambooshoot: require('./resources/axiecards/bamboo-clan.png'),
    goldenshell: require('./resources/axiecards/eggbomb.png'),
    imp: require('./resources/axiecards/ivory-stab.png'),
    incisor: require('./resources/axiecards/disarm.png'),
    kendama: require('./resources/axiecards/ivory-stab.png'),
    kestrel: require('./resources/axiecards/headshot.png'),
    lagging: require('./resources/axiecards/mystic-rush.png'),
    laggingggggg: require('./resources/axiecards/mystic-rush.png'),
    leafbughorn: require('./resources/axiecards/disguise.png'),
    littlebranch: require('./resources/axiecards/branch-charge.png'),
    merry: require('./resources/axiecards/merry-legion.png'),
    oranda: require('./resources/axiecards/heros-bane.png'),
    p4r4s1t3: require('./resources/axiecards/third-glance.png'),
    parasite: require('./resources/axiecards/third-glance.png'),
    pinkuunko: require('./resources/axiecards/poo-fling.png'),
    pocky: require('./resources/axiecards/sugar-rush.png'),
    rosebud: require('./resources/axiecards/healing-aroma.png'),
    santasgift: require('./resources/axiecards/prickly-trap.png'),
    scalyspear: require('./resources/axiecards/scaly-lunge.png'),
    scalyspoon: require('./resources/axiecards/tiny-catapult.png'),
    shoalstar: require('./resources/axiecards/star-shuriken.png'),
    sprucespear: require('./resources/axiecards/scaly-lunge.png'),
    strawberryshortcake: require('./resources/axiecards/sweet-party.png'),
    tealshell: require('./resources/axiecards/deep-sea-gore.png'),
    trump: require('./resources/axiecards/air-force-one.png'),
    umaibo: require('./resources/axiecards/sugar-rush.png'),
    unko: require('./resources/axiecards/poo-fling.png'),
    watermelon: require('./resources/axiecards/seed-bullet.png'),
    winghorn: require('./resources/axiecards/smart-shot.png'),
    winterbranch: require('./resources/axiecards/branch-charge.png'),
    yorishiro: require('./resources/axiecards/wooden-stab.png'),
    pliers: require('./resources/axiecards/dull-grip.png'),

    // Mouth
    axiekiss: require('./resources/axiecards/death-mark.png'),
    catfish: require('./resources/axiecards/swallow.png'),
    confident: require('./resources/axiecards/self-rally.png'),
    cutebunny: require('./resources/axiecards/terror-chomp.png'),
    dango: require('./resources/axiecards/chomp.png'),
    doubletalk: require('./resources/axiecards/soothing-song.png'),
    feastingmosquito: require('./resources/axiecards/blood-taste.png'),
    geisha: require('./resources/axiecards/crimson-water.png'),
    goda: require('./resources/axiecards/piercing-sound.png'),
    herbivore: require('./resources/axiecards/vegan-diet.png'),
    humorless: require('./resources/axiecards/vegetal-bite.png'),
    kawaii: require('./resources/axiecards/terror-chomp.png'),
    kotaro: require('./resources/axiecards/kotaro-bite.png'),
    lam: require('./resources/axiecards/angry-lam.png'),
    lamhandsome: require('./resources/axiecards/angry-lam.png'),
    littleowl: require('./resources/axiecards/dark-swoop.png'),
    mosquito: require('./resources/axiecards/blood-taste.png'),
    mrdoubletalk: require('./resources/axiecards/soothing-song.png'),
    nutcrackermouth: require('./resources/axiecards/nut-crack.png'),
    peacemaker: require('./resources/axiecards/peace-treaty.png'),
    pincer: require('./resources/axiecards/sunder-claw.png'),
    piranha: require('./resources/axiecards/crimson-water.png'),
    razorbite: require('./resources/axiecards/why-so-serious.png'),
    riskyfish: require('./resources/axiecards/fish-hook.png'),
    rudolph: require('./resources/axiecards/drain-bite.png'),
    serious: require('./resources/axiecards/vegetal-bite.png'),
    silencewhisper: require('./resources/axiecards/forest-spirit.png'),
    skullcracker: require('./resources/axiecards/nut-crack.png'),
    squareteeth: require('./resources/axiecards/mite-bite.png'),
    tinycarrot: require('./resources/axiecards/chomp.png'),
    tinyturtle: require('./resources/axiecards/chomp.png'),
    toothlessbite: require('./resources/axiecards/sneaky-raid.png'),
    zigzag: require('./resources/axiecards/drain-bite.png'),

    // Back
    indianstarmystic: require('./resources/axiecards/bulkwark.png'),
    anemoneback: require('./resources/axiecards/aqua-vitality.png'),
    balloon: require('./resources/axiecards/balloon-pop.png'),
    bidens: require('./resources/axiecards/cleanse-scent.png'),
    bluemoon: require('./resources/axiecards/scale-dart.png'),
    bonesail: require('./resources/axiecards/ivory-chop.png'),
    buzzbuzz: require('./resources/axiecards/bug-noise.png'),
    candycanes: require('./resources/axiecards/barb-strike.png'),
    croc: require('./resources/axiecards/nile-strike.png'),
    crystalhermit: require('./resources/axiecards/shelter.png'),
    cupid: require('./resources/axiecards/heart-break.png'),
    frozenbucket: require('./resources/axiecards/bulkwark.png'),
    furball: require('./resources/axiecards/juggling-balls.png'),
    garishworm: require('./resources/axiecards/barb-strike.png'),
    goldfish: require('./resources/axiecards/swift-escape.png'),
    greenthorns: require('./resources/axiecards/vine-dagger.png'),
    hamaya: require('./resources/axiecards/revenge-arrow.png'),
    hermit: require('./resources/axiecards/shelter.png'),
    hero: require('./resources/axiecards/heroic-reward.png'),
    indianstar: require('./resources/axiecards/bulkwark.png'),
    jaguar: require('./resources/axiecards/nitro-leap.png'),
    kingfisher: require('./resources/axiecards/patient-hunter.png'),
    mint: require('./resources/axiecards/refresh.png'),
    origami: require('./resources/axiecards/heart-break.png'),
    perch: require('./resources/axiecards/refresh.png'),
    pigeonpost: require('./resources/axiecards/blackmail.png'),
    pinkturnip: require('./resources/axiecards/turnip-rocket.png'),
    pumpkin: require('./resources/axiecards/october-treat.png'),
    raven: require('./resources/axiecards/ill-omened.png'),
    redear: require('./resources/axiecards/slippery-shield.png'),
    riskybeast: require('./resources/axiecards/revenge-arrow.png'),
    ronin: require('./resources/axiecards/single-combat.png'),
    ruggedsail: require('./resources/axiecards/ivory-chop.png'),
    sandal: require('./resources/axiecards/bug-splat.png'),
    scarab: require('./resources/axiecards/scarab-curse.png'),
    shiitake: require('./resources/axiecards/shrooms-grace.png'),
    snailshell: require('./resources/axiecards/sticky-goo.png'),
    spikywing: require('./resources/axiecards/buzzing-wind.png'),
    sponge: require('./resources/axiecards/ship-wreck.png'),
    starryballoon: require('./resources/axiecards/balloon-pop.png'),
    starryshell: require('./resources/axiecards/sticky-goo.png'),
    timber: require('./resources/axiecards/woodman-power.png'),
    trifeather: require('./resources/axiecards/triple-threat.png'),
    trispikes: require('./resources/axiecards/spike-throw.png'),
    turnip: require('./resources/axiecards/turnip-rocket.png'),
    wateringcan: require('./resources/axiecards/aqua-stock.png'),
    yakitori: require('./resources/axiecards/shrooms-grace.png'),

    // Tail
    ant: require('./resources/axiecards/chemical-warfare.png'),
    carrot: require('./resources/axiecards/carrot-hammer.png'),
    cattail: require('./resources/axiecards/cattail-slap.png'),
    cloud: require('./resources/axiecards/puffy-smack.png'),
    cottontail: require('./resources/axiecards/luna-absorb.png'),
    decembersurprise: require('./resources/axiecards/jar-barrage.png'),
    escapedgecko: require('./resources/axiecards/critical-escape.png'),
    featherfan: require('./resources/axiecards/sunder-armor.png'),
    firtrunk: require('./resources/axiecards/tiny-swing.png'),
    fireant: require('./resources/axiecards/chemical-warfare.png'),
    fishsnack: require('./resources/axiecards/anesthetic-bait.png'),
    gerbil: require('./resources/axiecards/gerbil-jump.png'),
    gila: require('./resources/axiecards/neuro-toxin.png'),
    granmasfan: require('./resources/axiecards/cool-breeze.png'),
    grasssnake: require('./resources/axiecards/venom-spray.png'),
    gravelant: require('./resources/axiecards/numbing-lecretion.png'),
    hare: require('./resources/axiecards/hare-dagger.png'),
    hatsune: require('./resources/axiecards/leek-leak.png'),
    hotbutt: require('./resources/axiecards/spicy-surprise.png'),
    iguana: require('./resources/axiecards/scale-dart.png'),
    koi: require('./resources/axiecards/upstream-swim.png'),
    koinobori: require('./resources/axiecards/upstream-swim.png'),
    kurokoi: require('./resources/axiecards/upstream-swim.png'),
    maki: require('./resources/axiecards/anesthetic-bait.png'),
    namekcarrot: require('./resources/axiecards/carrot-hammer.png'),
    navaga: require('./resources/axiecards/flanking-smack.png'),
    nimo: require('./resources/axiecards/tail-slap.png'),
    nutcrackertail: require('./resources/axiecards/nut-throw.png'),
    omatsuri: require('./resources/axiecards/cool-breeze.png'),
    postfight: require('./resources/axiecards/all-out-shot.png'),
    potatoleaf: require('./resources/axiecards/aqua-deflect.png'),
    pupae: require('./resources/axiecards/grub-explode.png'),
    ranchu: require('./resources/axiecards/water-sphere.png'),
    rice: require('./resources/axiecards/night-steal.png'),
    sakuracottontail: require('./resources/axiecards/luna-absorb.png'),
    shiba: require('./resources/axiecards/rampant-howl.png'),
    shrimp: require('./resources/axiecards/chitin-jump.png'),
    snakejar: require('./resources/axiecards/jar-barrage.png'),
    snowyswallow: require('./resources/axiecards/early-bird.png'),
    swallow: require('./resources/axiecards/early-bird.png'),
    tadpole: require('./resources/axiecards/black-bubble.png'),
    thelastone: require('./resources/axiecards/risky-feather.png'),
    thornycaterpillar: require('./resources/axiecards/allergic-reaction.png'),
    tinydino: require('./resources/axiecards/tiny-swing.png'),
    twintail: require('./resources/axiecards/twin-needle.png'),
    wallgecko: require('./resources/axiecards/critical-escape.png'),
    yam: require('./resources/axiecards/gas-unleash.png')
    
};

ReactDOM.render(
    <React.StrictMode>
        <App/>
    </React.StrictMode>,
    document.getElementById("root")
);

export default images;